### ISSUE TITLE
Crypto Revolution Token Logo

### ISSUE THREAD

**Issue by daniunss** [trustwallet/developer#138]
Hi guys. Please I neen my token logo to be visible. My friends told me people from Trust Wallet githib can help me
![Crypto Revolution Logo](https://user-images.githubusercontent.com/67890449/86559589-f7029d80-bf64-11ea-8ee4-c25b1f9a74a7.jpg)
](url)

**Comment by daniunss** [comment]
Thank you in advance if someone will help :)

**Comment by vikmeup** [comment]
Wrong repo, see: https://developer.trustwallet.com/add_new_asset
