### ISSUE TITLE
Update walletconnect/dapp page

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/developer#146]
doc link: https://developer.trustwallet.com/wallet-connect/dapp
`@trustwallet/walletconnect` was deprecated, we can simply suggest user to use official walletconnect lib, and add helpers (https://github.com/trustwallet/web-core/blob/master/packages/walletconnect/src/index.ts)  to the sample code

**Comment by roy1210** [comment]
Hi Team.
Would you mind advising ETA of this issue? Your reply is much appreciated.

**Comment by hewigovens** [comment]
@leoneparise will work on this soon

**Comment by roy1210** [comment]
Thank you @hewigovens  
@leoneparise Kindly let me know once docs are updated!

**Comment by roy1210** [comment]
@leoneparise it would be greatly appreciated if you can add a `timelock` order's sample code on the docs as well :D

**Comment by losnappas** [comment]
So how much of the page is outdated now?

https://developer.trustwallet.com/wallet-connect/dapp#sign-transaction -- how should do I do that now?

And are there new methods? Such as "send transaction", not just sign.

The repository you linked for helpers is marked read-only. Is that really where I'm supposed to use stuff from?

Would love to see some examples.

**Comment by roy1210** [comment]
Hi @hewigovens @leoneparise  @losnappas 
May I know ETA for updating docs for Dapp page?
