### ISSUE TITLE
Support Binance order

### ISSUE THREAD

**Issue by roy1210** [trustwallet/developer#148]
Hi @hewigovens and team.
Thank you for updating [docs for Dapp page](https://developer.trustwallet.com/wallet-connect/dapp).

I have tried to run `freeze` order according to new instruction which is updated on the docs. But unfortunately, `._sendCallRequest(request)` is never going to return the `request`. After debugging, looks function is stacking on `utf8ToBytes` function forever. 
I think `method: 'trust_signTransaction',` is not working properly since `get_accounts` order is working well. 
This is my code to run freeze function. Kindly please check and advise. 
(Please feel free to clone the repo and reproduce this issue!)

Code: 
https://github.com/roy1210/beptool_fork/blob/feat/%40walletconnect/client/src/components/pages/Freezer.js#L161

Demo: 
https://beptool-fork-git-feat-walletconnectclient.roy1210.vercel.app/

P.S. 
The old library, `@trustwallet/walletconnect` will handle `freeze` order without any issue. Hence, kindly investigate how this issue happens. Maybe missing something in my code?? Much appreciate if you can add an example of Binance orders as well.  Thank you!

Code (Using @trustwallet/walletconnect): https://github.com/roy1210/beptool_fork/blob/feat/%40trustwallet/walletconnect/src/components/pages/Freezer.js#L150

Demo: 
https://beptool-fork-git-feat-trustwalletwalletconnect.roy1210.vercel.app/

```
const request = connector._formatRequest({
    method: 'trust_signTransaction',
    params: [
        {
            network,
            transaction: JSON.stringify(tx),
        },
    ],
});

connector
 // Memo: Didn't return anything
  ._sendCallRequest(request)
  .then(result => {
    // Returns transaction signed in json or encoded format
    console.log(result);
  })
  .catch(error => {
    // Error returned when rejected
    console.error(error);
  });
```
<img width="1157" alt="Screenshot 2020-10-14 at 12 52 50 AM" src="https://user-images.githubusercontent.com/42575132/95893360-713f8b00-0dba-11eb-8fe4-ea462e195370.png">

**Comment by hewigovens** [comment]
where is `utf8ToBytes` function call? could you please try to create `tx` with wallet core proto? https://github.com/trustwallet/wallet-core/blob/master/typescript/tests/index.test.ts#L48

`@trustwallet/walletconnect` is old wallet connect version, maybe something breaks in latest walletconnect version

**Comment by roy1210** [comment]
Hi @hewigovens !

What I am trying to say is both 2 branch I showed in above is 99% same code. 

The only difference is using `@trustwallet/walletconncet` or `@walletconnect/client`(According to the latest docs). 

The problem is `@trustwallet/walletconncet` works without any issue while `@walletconnect/client` is stacking on `.-sendCallRequest(request)` function. Both are the same `tx` object which followed [WalletCore's proto message]( https://github.com/trustwallet/wallet-core/blob/master/src/proto/Binance.proto#L88).

So do you think it doesn't make sense the new wallet connect doesn't work while the old wallet connect version works well ?



> could you please try to create tx with wallet core proto? https://github.com/trustwallet/wallet-core/blob/master/typescript/tests/index.test.ts#L48

Do you mean make `tx` object by `TW.Binance.Proto.SigingInput.create()` ? then pass the `tx` to `transaction: JSON.stringify(tx)` in order to make `connector._formatRequest`? 

Would you mind making an example for `freeze order` with `TW.Binance.Proto.SigingInput.create()` ? That would be much appreciated since there is no documentation and example code in `wallet-core/typescript`!

 (btw, I think `privateKey` is not able to get from outside of the Trust wallet app.)



> where is utf8ToBytes function call?

This function is called after `.-sendCallRequest(request)`. I think maybe called by `@walletconnect/client` library.

**Comment by hewigovens** [comment]
ok, will try to debug it later this week, meanwhile https://github.com/thorchain/bepswap-web-ui might help you

**Comment by roy1210** [comment]
Thank you very much for your support.
Yes, I checked this repo when I debugging before.  :D
Looks like they are using [the old library `@trustwallet/walletconnect: 0.0.12` too](https://github.com/thorchain/bepswap-web-ui/blob/development/package.json#L46). 

Looking forward to seeing your example code! 
After trying the freeze order with the new `@walletconnect/client`, I’ll try to apply `timelock order` again!

**Comment by roy1210** [comment]
Hi @hewigovens 

I found the reason why `.-sendCallRequest(request)` didn't success.
It's my bad. I didn't set `network` property in here.

```
const request = connector._formatRequest({
    method: 'trust_signTransaction',
    params: [
        {
           // Should be `network: NETWORK_ID,` instead of `NETWORK_ID`
            NETWORK_ID,
            transaction: JSON.stringify(tx),
        },
    ],
});
```

After fixed `network`, the freeze order was running successfully!

**Comment by roy1210** [comment]
@hewigovens 
> could you please try to create tx with wallet core proto? https://github.com/trustwallet/wallet-core/blob/master/typescript/tests/index.test.ts#L48

I have tried to create `txInput` by `wallet-core` but didn't success due to `Error: TypeError: Cannot read property 'prototype' of null`. Could you kindly advise where I missed in [this](https://github.com/roy1210/beptool_fork/blob/feat/%40walletconnect/client/src/components/pages/Freezer.js#L153) code, please?

```
// Error: TypeError: Cannot read property 'prototype' of null
          const txInput = TW.Binance.Proto.SigningInput.create({
            chainId: "Binance-Chain-Tigris",
            accountNumber: account.account_number.toString(),
            sequence: account.sequence.toString(),
            freezeOrder: {
              from: addr,
              symbol: selectedCoin,
              amount: amount,
            }
          })

          console.log("txInput", txInput);
          const request = context.wallet.walletconnect._formatRequest({
            method: "trust_signTransaction",
            params: [
              {
                network: NETWORK_ID,
                transaction: txInput,
              },
            ],
          });
```
Ref: [core_proto.d.ts](https://gist.github.com/roy1210/99d0460bd7dc9fed060f209f6fdc6c33#file-core_proto-d-ts-L1738)

Values:
<img width="1779" alt="Screenshot 2020-10-14 at 11 23 12 PM" src="https://user-images.githubusercontent.com/42575132/96015563-47e63400-0e7a-11eb-8b8e-739b37d14c61.png">

Not sure if this is the problem.
![image](https://user-images.githubusercontent.com/42575132/96015592-53d1f600-0e7a-11eb-87bd-fde90616df24.png)

**Comment by hewigovens** [comment]
hey,  I can receive freeze/timeLock order after correcting the types: https://github.com/roy1210/beptool_fork/pull/3

**Comment by roy1210** [comment]
@hewigovens Thank you very much!!! Let me study later!!

**Comment by roy1210** [comment]
Hi @hewigovens 
Looks like `signed timeLock msg` is invalided in your PR too. It's same error, `Error: msg should not be nil`. 
Kindly check my [reply](https://github.com/roy1210/beptool_fork/pull/3). 
Once again, thank you very much for your help!

**Comment by hewigovens** [comment]
@catenocrypt can you help confirm that timeLockOrder is working on mainnet (manually sign a tx with wallet core), or just some data not set correctly

**Comment by roy1210** [comment]
@hewigovens 
By the way, my wallet app version is 5.0. Do you think `timelock` order should work in this APP version?
![image](https://user-images.githubusercontent.com/42575132/96123504-7c62fa00-0f25-11eb-8e24-11a363ac2c0c.png)

**Comment by hewigovens** [comment]
Yes please always try latest build, we have pushed new release to App Store

**Comment by roy1210** [comment]
@hewigovens 
Should I download from App Store(ver5.2) or from TestFlight(ver5.0)?

**Comment by roy1210** [comment]
![image](https://user-images.githubusercontent.com/42575132/96205308-d7820480-0f98-11eb-98e0-fc20fd9395e9.jpeg)

**Comment by roy1210** [comment]
@catenocrypt 
Much appreciated if you can test timelock function with your TW app :D

**Comment by roy1210** [comment]
Hi @hewigovens, @catenocrypt 

(↓ Same as my comment in [this PR](https://github.com/roy1210/beptool_fork/pull/3))
I have found a way to achieve `timelock` with `wallet-core`. Basically I did following 2 approach to make it.

- Use the client directly with a call to ‘client.tokens.timeLock’. (Which provide by Binance JS SDK)
- Set a signing delegate on the client that calls into WalletConnect class instance. 

However, `time relock` and `time unlock` are not working due to return `Error: signature verification failed`.
I guess `wallet-core` library has a problem to run `time relock` and `time unlock`.
Kindly please help to check it. Thanks!

(Maybe a problem with [id](https://github.com/trustwallet/wallet-core/blob/master/src/proto/Binance.proto#L182) in somewhere in the library? Because `timelock_order` is working well without `id`...)

![image](https://user-images.githubusercontent.com/42575132/96346379-11085c00-10ce-11eb-98c4-e53f8b4eba04.png)

**Comment by hewigovens** [comment]
Hey @roy1210 , I found the problem, it is caused by `id`, will push a fix to wallet core soon, Thanks for you detail and patience debugging!

**Comment by roy1210** [comment]
Hi @hewigovens @catenocrypt 
Thank you for your investigate!

There is one more thing `wallet-core` should aware about `time relock`.
When a user want to `relock` with same amount as original locked value, Binance chain assume `null` or `[]` (just empty array) in parameter of [amount](https://github.com/trustwallet/wallet-core/blob/efd4a0e26c132253f3bbf1b0b4834c314a35e084/src/proto/Binance.proto#L178).

This issue might be helpful to explain.
https://github.com/binance-chain/node-binary/issues/254

And this is our fix in our fork of `Binance JS SDK` may help to explain this:
https://github.com/SwingbyProtocol/javascript-sdk/commit/898215c4d82dc167c4da4acd37b6b525095d5f37

I’m not seeing anything about the case where [coins](https://github.com/trustwallet/wallet-core/blob/efd4a0e26c132253f3bbf1b0b4834c314a35e084/src/proto/Binance.proto#L49) is omitted. Since it’s repeated in the [PB message](https://github.com/trustwallet/wallet-core/blob/efd4a0e26c132253f3bbf1b0b4834c314a35e084/src/proto/Binance.proto#L178), it’s essentially an array. It should become `null` or `[]` in the json sign doc when empty for the purpose of `relocking` with the same amount.

**Comment by hewigovens** [comment]
relock test also added: https://github.com/trustwallet/wallet-core/pull/1143

**Comment by roy1210** [comment]
Hi @hewigovens 
Thank you for your update!
May I know estimated when I can try new version of wallet-core to try `time relock` and `time unlock`?

**Comment by hewigovens** [comment]
will let you know once we have new iOS build

**Comment by roy1210** [comment]
Noted and thank you!

**Comment by roy1210** [comment]
Hi @hewigovens 
Sorry for asking again, when can I try the latest version of TW or wallet-core for "time relock" and "time unlock" ?

**Comment by roy1210** [comment]
@hewigovens 
The latest version of TW is supporting `timelock`, `relock`and `unlock` order. 
Thank you for your great support!!
