### ISSUE TITLE
[Bitcoin] pass window.bitcoin object to dapp browser

### ISSUE THREAD

**Issue by noxonsu** [trustwallet/developer#152]
**Is your feature request related to a problem? Please describe.**
Hi, our Atomic Swap dapp interact with bitcoin blockchain, but now trustwallet doesn't have any API for this

**Describe the solution you'd like**
would be great if trustwallet's dapp browser pass `window.bitcoin` object to dapp

simplest example: 
```
window.bitcoin.address
>16bFRqtBivrvdBi37kxPtiSUH5qWwaoH15
```

also woukd be great if ```<a href="bitcoin:16bFRqtBivrvdBi37kxPtiSUH5qWwaoH15?amount=0.001">pay 0.001</a>``` works too (or somt like `window.bitcoin.send`...

**Describe alternatives you've considered**
(i tried deep link `https://link.trustwallet.com/send...` but no success ). 

**Additional context**

**Comment by hewigovens** [comment]
This issue is not really related to wallet core, transferred to developer repo

**Comment by vikmeup** [comment]
Not short terms plans to currently supported this functionality
