### ISSUE TITLE
Merge-Fee-Bot issue with Contractor Format Error

### ISSUE THREAD

**Issue by spacegrime** [trustwallet/developer#176]
I'm receiving an error from merge-bot that the contract format is invalid. I renamed the file temporarily to a different name and then correctly to the one that the bot suggested. Despite this, I still get an error. Please advise.

regarding this file location: https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets
Contract address: 0x89671544190eE39E469C8393009875dF6565457a

**Comment by spacegrime** [comment]
Additionally, we just received a notification that our pull request failed. Can you provide additional detail into this and how we can resolve it? Screenshot attached for reference.
![Screen Shot 2021-05-13 at 9 28 07 PM](https://user-images.githubusercontent.com/83896787/118221280-29591300-b432-11eb-816c-04e11b6ed784.png)

**Comment by spacegrime** [comment]
@vikmeup Can you provide insight to why this is closed? We haven't received a notification of resolution.

**Comment by vikmeup** [comment]
tag me in the pull requests that you created

**Comment by catenocrypt** [comment]
You need to scroll further up, check the whole output of the build step, and you will see the error details.
Please next time specify the PR number/link, it helps a lot in investigation :)
