### ISSUE TITLE
Lost funds

### ISSUE THREAD

**Issue by Iktaha** [trustwallet/developer#192]
Hi, I was transferring funds #fantom from Trust Wallet to  Binance like I did the previous 2 times, but this time around, the transaction was stuck on pending and nothing was showing up on block chain explorer either so I reimported my wallet like the guide on the Trust Wallet forum. After reimporting, my pending transaction disappeared and the amount of funds I was transferring have vanished as well. They’ve been deducted from my Trust Wallet without the transaction actually going through. What should I do now to get lost crypto back

**Comment by vikmeup** [comment]
You can see details of your transfers on public explorers: https://explorer.solana.com/

**Comment by Iktaha** [comment]
Sounds like u don't even read my massage

**Comment by vikmeup** [comment]
> Sounds like u don't even read my massage

Can you provide details of your address, transaction transfer or any information that can help debug the issue?

**Comment by Iktaha** [comment]
Hello , 
This my receiving fantom address 

0xdaf3Fc19235D9F49EC79b7D0A2A60CBE6915C105

And if check fantom newwork 
You will not found  6.840 FTM I sent. Because it’s get failed from trust wallet. And not getting back to my funds. 
 I still have screenshot from trust wallet

**Comment by vikmeup** [comment]
https://ftmscan.com/address/0xdaf3Fc19235D9F49EC79b7D0A2A60CBE6915C105 - I do not see any transfer with 6.8 FTM, but there is many other transactions 

If someone sent you 6.84 FTM and you never received, then you need to contact the sender.

**Comment by Iktaha** [comment]
It’s not some one send me
I send from my trust wallet account to Binance 

6.840 fontm 

Pls provide me your telegram account to send you screenshot of trust wallet when transaction get failed

**Comment by Iktaha** [comment]
So if you check here 

https://ftmscan.com/address/0xdaf3Fc19235D9F49EC79b7D0A2A60CBE6915C105

You will not found the 6840 fantom I sent, so they still blocked in trust wallet server 
,
Kindly let me know if u see the screenshot I sent

**Comment by vikmeup** [comment]
You need to contact the sender, there is nothing to do with Trust Wallet.

**Comment by Iktaha** [comment]
The sender said u should talk to trustwallet 
Transaction get failed from the app. And the app doesn't give any information

**Comment by vikmeup** [comment]
> The sender said u should talk to trustwallet Transaction get failed from the app. And the app doesn't give any information
> […](#)
> Sent from my iPhone
> On 18 Sep 2021, at 09:21, Viktor Radchenko ***@***.***> wrote: ﻿ You need to contact the sender, there is nothing to do with Trust Wallet. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

As suggested before, it's not the app. Transaction never been completed on the blockchain level, here is the proof: https://ftmscan.com/address/0xdaf3Fc19235D9F49EC79b7D0A2A60CBE6915C105.
