### ISSUE TITLE
Add validator into Trust Wallet

### ISSUE THREAD

**Issue by fongchunwee** [trustwallet/developer#196]
Hi,
Want to add validator into Trust Wallet to enable user to delegate tokens.
Name : KysenPool

**Comment by vikmeup** [comment]
You would need to add it here: https://github.com/trustwallet/assets/tree/master/blockchains/cosmos/validators

Details: https://developer.trustwallet.com/assets/new-asset

**Comment by fongchunwee** [comment]
thank you very much
