### ISSUE TITLE
Use Multilingual in Trust Wallet 

### ISSUE THREAD

**Issue by luckymehndiratta** [trustwallet/developer#199]
Hi Team,
As we are working with the iOS SDK. We need to change the language of the mnemonic show to the user and pass the same to the SDK base on the user-selected language(English, Chinese, Japanese). So Please give us the break in how we will do it.

**Comment by catenocrypt** [comment]
Trust Wallet only supports English language for BIP39 mnemonics (as it is recommended by the BIP 39 itself).  One can use wallet-core HDWallet with arbitrary mnemonics with explicit 'no check' option, but that must be used with great care.
