### ISSUE TITLE
Create docc repo and publish Wallet Core swift docc

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/developer#253]
Todo:

- [x] Create `docc` repo under Trust
- [x] Create `main` and `gh-pages` branch
- [x] Add GitHub Action
- - [x] manual dispatch action (tag name)
- - [x] pull tag and process it
- - [x] commit to `gh-pages`

```shell
$(xcrun --find docc) process-archive \
transform-for-static-hosting PATH_TO_DOARCHIVE_FILE \
--output-path PATH_TO_SAVE_FILES \
--hosting-base-path URL_BASE_PATH

#URL_BASE_PATH=docc
```

Reference:
- https://github.com/apple/swift-markdown/blob/main/bin/update-gh-pages-documentation-site#L36
- https://gist.github.com/alfianlosari/9469a4d0ddf528355cdd64513999f431

**Comment by Anonymous-User-c4676** [comment]
0x89150b3c4e64da574abc529aab194b5b9df7f66d

**Comment by hewigovens** [comment]
published on https://trustwallet.github.io/docc/documentation/walletcore/
