### ISSUE TITLE
Add Validator Onboarding

### ISSUE THREAD

**Issue by wpank** [trustwallet/developer#40]
Create a section for Platform and list the process of onboarding a validator:

- in each `assets/blockchain/<chain> /validators/list.json, add a `name`, `id`, `description`, and `website`. 
- in each `assets/blockchain/<chain>/validators/assets/<validator_address>` add a 256x256 pixel `logo.png` file.

**Comment by kolya182** [comment]
Added here https://github.com/trustwallet/developer/commit/3e806d267fe5c85997b9e1df73aa33f2346fc8c9#diff-09afa21939ecb9da5c08955b02f008d5R35
