### ISSUE TITLE
Add link to Trust Developers Telegram Chat

### ISSUE THREAD

**Issue by marioabcdef** [trustwallet/developer#55]
![image](https://user-images.githubusercontent.com/12964883/66578051-b2370b00-eb7a-11e9-9c0e-af2ca81a352a.png)
![image](https://user-images.githubusercontent.com/12964883/66578124-d2ff6080-eb7a-11e9-9ff4-d7896c309a59.png)

We should add a link to https://t.me/walletcore here, any thoughts?

**Comment by vikmeup** [comment]
@hewigovens any idea where to add this button? there is many options atm, already confusing?

**Comment by hewigovens** [comment]
Index page should be fine, under Get Started

**Comment by vikmeup** [comment]
Can you add and let’s close it?
