### ISSUE TITLE
Better wallet core integration guide / example app

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/developer#69]
- [x] How to use wallet core library in iOS/macOS/Android/C++ app
- [x] Create HD wallet
- - [x] introduce BIP39/BIP44
- [x] Get private key by path / coin
- [x] Get BTC/ETH/BNB address
- [x] Sign tx, explain each field in signing input, how to get them from RPC
- - [x] BTC
- - [x] ETH
- - [x] BNB

**Comment by catenocrypt** [comment]
I have completed the sample app with transaction signing (AnySigner).
I propose to keep this sample as a separate repo (to see how small it is), and transfer it to under trustwallet org.
https://github.com/catenocrypt/sample-wallet-core-cpp

**Comment by hewigovens** [comment]
I have similar repos: https://github.com/hewigovens/WalletCoreExample, maybe we can put it together? only implement a few key methods

**Comment by hewigovens** [comment]
document is also important, explains each step with btc/eth/bnb

**Comment by catenocrypt** [comment]
Some remaining TODO:
- move sample app in github from my name to trustwallet
- create sample Android app — I will ask the android guys for help
- Bitcoin signing example (to the Usage Guide, at least in swift)
- BInance signing example (to the Usage Guide, at least in swift)
